IAMRoleRedshiftServerless:
  Type: 'AWS::IAM::Role'
  Properties:
    RoleName: !Sub ${Environment}-redshift-serverless-role
    AssumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            Service:
              [firehose.amazonaws.com, redshift.amazonaws.com, glue.amazonaws.com, redshift-serverless.amazonaws.com]
          Action: 'sts:AssumeRole'
    MaxSessionDuration: 3600
    Policies:
      - PolicyName: !Sub ${Environment}-redshift-serverless-policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - 's3:AbortMultipartUpload'
                - 's3:GetBucketLocation'
                - 's3:GetObject'
                - 's3:ListBucket'
                - 's3:ListBucketMultipartUploads'
                - 's3:PutObject'
              Resource:
                - !Sub 'arn:aws:s3:::${RawLayerBucket}'
                - !Sub 'arn:aws:s3:::${RawLayerBucket}/*'
                - !Sub 'arn:aws:s3:::${StageLayerBucket}'
                - !Sub 'arn:aws:s3:::${StageLayerBucket}/*'
            - Effect: Allow
              Resource: !Sub arn:aws:glue:eu-west-2:${AWS::AccountId}:*
              Action:
                - 'glue:GetTable'
                - 'glue:GetTables'
                - 'glue:GetDatabase'
                - 'glue:GetDatabases'
                - 'glue:GetPartitions'

RedshiftSecret:
  Type: 'AWS::SecretsManager::Secret'
  Properties:
    Description: This is a Secrets Manager secret for a Redshift cluster
    GenerateSecretString:
      # based on https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_secret_json_structure.html#reference_secret_json_structure_RS
      SecretStringTemplate: !Sub |
        {
          "engine": "redshift",
          "host": "${Environment}-redshift-serverless-workgroup.${AWS::AccountId}.${AWS::Region}.redshift-serverless.amazonaws.com",
          "username": "admin",
          "dbname": "${Environment}-redshift",
          "port": "5439"
        }
      GenerateStringKey: password
      PasswordLength: !Ref RedshiftSecretLength
      ExcludeCharacters: !Ref RedshiftSecretExcludeCharacters
    KmsKeyId: !Ref KmsKey
    Tags:
      - Key: RedshiftUser
        Value: admin

RedshiftSecretRotationSchedule:
  Type: AWS::SecretsManager::RotationSchedule
  DependsOn: RedshiftSecretRotationLambdaPermission
  Properties:
    RotationLambdaARN: !GetAtt RedshiftSecretRotationLambda.Arn
    RotationRules:
      ScheduleExpression: cron(0 2 1 * ? *) # the first day of every month at 2am
    SecretId: !Ref RedshiftSecret

RedshiftSecretRotationLambda:
  # checkov:skip=CKV_AWS_116: DLQ not needed
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: redshift-rotate-secret
    Handler: redshift-rotate-secret.handler
    Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          - Effect: Allow
            Action:
              - 'sqs:DeleteMessage'
              - 'sqs:GetQueueAttributes'
              - 'sqs:ReceiveMessage'
            Resource: !If [UsePlaceholderTxMAQueue, !GetAtt EventConsumerQueue.Arn, '{{resolve:ssm:TxMAEventQueueARN}}']
          - Effect: Allow
            Action:
              - secretsmanager:DescribeSecret
              - secretsmanager:GetSecretValue
              - secretsmanager:PutSecretValue
              - secretsmanager:UpdateSecretVersionStage
            Resource: !Ref RedshiftSecret
          - Effect: Allow
            Action: secretsmanager:GetRandomPassword
            Resource: '*'
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:GenerateDataKey
            Resource: !GetAtt KmsKey.Arn
            Condition:
              StringEquals:
                kms:EncryptionContext:SecretARN: !Ref RedshiftSecret
    ReservedConcurrentExecutions: 10
    Environment:
      # checkov:skip=CKV_AWS_173: These environment variables do not require encryption
      Variables:
        PASSWORD_LENGTH: !Ref RedshiftSecretLength
        PASSWORD_EXCLUDE_CHARS: !Ref RedshiftSecretExcludeCharacters
        ENVIRONMENT: !Ref Environment
    Tags:
      Environment: !Ref Environment
    MemorySize: 256
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup
        - !Ref RedshiftAccessEC2SecurityGroup
      SubnetIds:
        - !Ref SubnetForDAP1
        - !Ref SubnetForDAP2
        - !Ref SubnetForDAP3

RedshiftSecretRotationLambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref RedshiftSecretRotationLambda
    Action: lambda:InvokeFunction
    Principal: secretsmanager.amazonaws.com
    SourceArn: !Ref RedshiftSecret

RedshiftServerlessNamespace:
  Type: 'AWS::RedshiftServerless::Namespace'
  Properties:
    AdminUsername: !Sub '{{resolve:secretsmanager:${RedshiftSecret}::username}}'
    AdminUserPassword: !Sub '{{resolve:secretsmanager:${RedshiftSecret}::password}}'
    DbName: !Sub '{{resolve:secretsmanager:${RedshiftSecret}::dbname}}'
    DefaultIamRoleArn: !GetAtt IAMRoleRedshiftServerless.Arn
    IamRoles:
      - !GetAtt IAMRoleRedshiftServerless.Arn
    KmsKeyId: !Ref KmsKey
    FinalSnapshotName: !Sub '${Environment}-redshift-snapshot'
    FinalSnapshotRetentionPeriod: 30
    LogExports:
      - useractivitylog
    NamespaceName: !Sub '${Environment}-redshift-serverless-ns'

RedshiftServerlessWorkgroup:
  Type: 'AWS::RedshiftServerless::Workgroup'
  Properties:
    BaseCapacity: 64
    EnhancedVpcRouting: false
    NamespaceName: !Ref RedshiftServerlessNamespace
    Port: !Sub '{{resolve:secretsmanager:${RedshiftSecret}::port}}'
    PubliclyAccessible: false
    SubnetIds:
      - !Ref SubnetForDAP1
      - !Ref SubnetForDAP2
      - !Ref SubnetForDAP3
    WorkgroupName: !Sub '${Environment}-redshift-serverless-workgroup'

RedshiftAccessEC2InstanceProfile:
  Type: AWS::IAM::InstanceProfile
  Properties:
    InstanceProfileName: !Sub ${Environment}-dap-redshift-access-server-instance-profile
    Roles:
      - !Ref RedshiftAccessEC2Role

RedshiftAccessEC2SecurityGroup:
  Type: 'AWS::EC2::SecurityGroup'
  Properties:
    GroupDescription: 'Security Group for Redshift Access EC2'
    VpcId: !Ref VPCForDAP
    SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
        Description: Allow egress to anywhere

VPCDefaultSecurityGroupRedshiftIngress:
  Type: AWS::EC2::SecurityGroupIngress
  Properties:
    GroupId: !GetAtt VPCForDAP.DefaultSecurityGroup
    IpProtocol: tcp
    FromPort: 5439
    ToPort: 5439
    SourceSecurityGroupId: !Ref RedshiftAccessEC2SecurityGroup
    Description: Allow ingress into the VPC default security group for redshift traffic from the redshift access security group

RedshiftAccessEC2LaunchTemplate:
  Type: 'AWS::EC2::LaunchTemplate'
  Properties:
    LaunchTemplateName: RedshiftAccessEC2LaunchTemplate
    LaunchTemplateData:
      ImageId: 'ami-0ab07a60473831856'
      InstanceType: 't2.nano'
      IamInstanceProfile:
        Arn: !GetAtt RedshiftAccessEC2InstanceProfile.Arn
      SecurityGroupIds:
        - !Ref RedshiftAccessEC2SecurityGroup
      MetadataOptions:
        HttpTokens: 'required'
        HttpPutResponseHopLimit: 1
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 64

RedshiftAccessEC2:
  Type: 'AWS::EC2::Instance'
  Properties:
    LaunchTemplate:
      LaunchTemplateName: RedshiftAccessEC2LaunchTemplate
      Version: !GetAtt RedshiftAccessEC2LaunchTemplate.LatestVersionNumber
    SubnetId: !Ref SubnetForDAP1

RedshiftAccessEC2Role:
  Type: AWS::IAM::Role
  Properties:
    RoleName: !Sub ${Environment}-dap-redshift-access-server-role
    AssumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

RedshiftMigrationRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: !Sub ${Environment}-dap-redshift-migrate-role
    AssumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
          Action: 'sts:AssumeRoleWithWebIdentity'
          Condition:
            StringLike:
              'token.actions.githubusercontent.com:sub':
                - repo:govuk-one-login/data-analytics-platform:ref:refs/heads/*
                - repo:govuk-one-login/data-analytics-platform:environment:*
    Policies:
      - PolicyName: !Sub ${Environment}-dap-redshift-migrate-policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: secretsmanager:ListSecrets
              Resource: '*'
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref RedshiftSecret
            - Effect: Allow
              Action: redshift-serverless:GetWorkgroup
              Resource: !GetAtt RedshiftServerlessWorkgroup.Workgroup.WorkgroupArn
            - Effect: Allow
              Action: kms:Decrypt
              Resource: !GetAtt KmsKey.Arn
            - Effect: Allow
              Action: ssm:StartSession
              Resource:
                - arn:aws:ssm:eu-west-2::document/AWS-StartPortForwardingSessionToRemoteHost
                - !Sub arn:aws:ec2:eu-west-2:${AWS::AccountId}:instance/${RedshiftAccessEC2}
            - Effect: Allow
              Action: ec2:DescribeInstances
              Resource: '*'
