external-checks-git:
  - https://github.com/alphagov/di-devplatform-checkov-hook.git//src/gds_digitalidentity_checkovhook/custom_policies
  - https://github.com/alphagov/di-devplatform-checkov-hook.git//src/gds_digitalidentity_checkovhook/custom_policies_precommit
