external-checks-git:
  - https://github.com/govuk-one-login/devplatform-checkov-hook.git//src/gds_digitalidentity_checkovhook/custom_policies
  - https://github.com/govuk-one-login/devplatform-checkov-hook.git//src/gds_digitalidentity_checkovhook/custom_policies_precommit
