AWSTemplateFormatVersion: '2010-09-09'
Description: Data and Analytics Stack
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: Environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - build
      - staging
      - integration
      - production
  CodeSigningConfigArn:
    Description: ARN of Code Signing Config from deployment pipeline
    Type: String
    Default: none
  PermissionsBoundary:
    Description: ARN of permissions boundary for new roles
    Type: String
    Default: none

Conditions:
  UseCodeSigning: !Not [!Equals [!Ref CodeSigningConfigArn, none]]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, none]]

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    Runtime: nodejs18.x
    Timeout: 30
    CodeUri: dist/
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps

Resources:
  EventQueue:
    # checkov:skip=CKV_AWS_27: This is a temporary test queue
    Type: AWS::SQS::Queue
    Properties:
      QueueName: txma-event-queue

  EventConsumerLambda:
    # checkov:skip=CKV_AWS_116: DLQ not needed for lambda driven by SQS
    # checkov:skip=CKV_AWS_117: VPC not needed for lambda
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: txma-event-consumer
      Events:
        CleanEvent:
          Type: SQS
          Properties:
            BatchSize: 1
            Queue: !GetAtt EventQueue.Arn
      Handler: txma-event-consumer.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:ReceiveMessage
              Resource: !GetAtt EventQueue.Arn
      ReservedConcurrentExecutions: 10
      Environment:
        # checkov:skip=CKV_AWS_173: These environment variables do not require encryption
        Variables:
          FIREHOSE_STREAM_NAME: !Sub txma-event-stream-${Environment}
      Tags:
        Environment: !Ref Environment

  TestSupportLambda:
    # checkov:skip=CKV_AWS_116: DLQ not needed for lambda driven by SQS
    # checkov:skip=CKV_AWS_117: VPC not needed for lambda
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test-support-${Environment}
      Handler: test-support.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*
            - Effect: Allow
              Action:
                - logs:FilterLogEvents
                - logs:GetLogEvents
              Resource: '*'
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource: !Sub arn:aws:s3:::${AWS::StackName}*
            - Effect: Allow
              Action: sqs:SendMessage
              Resource: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:*
      ReservedConcurrentExecutions: 10
      Tags:
        Environment: !Ref Environment
