AWSTemplateFormatVersion: 2010-09-09
Description: Data and Analytics Sustainability Stack
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: Environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
      - production-preview
  CodeSigningConfigArn:
    Description: ARN of Code Signing Config from deployment pipeline
    Type: String
    Default: none
  PermissionsBoundary:
    Description: ARN of permissions boundary for new roles
    Type: String
    Default: none

  # TestRoleArn:
  #   Type: String
  #   Description: The ARN of the role that will used by secure pipelines to run integration tests
  #   Default: none
  #   AllowedPattern: (none)|(arn:aws:iam::.*:role/.*)
  VpcStackName:
    Type: String
    Description: The name of the stack containing the VPC
    Default: none

Conditions:
  UseCodeSigning: !Not
    - !Equals
      - !Ref CodeSigningConfigArn
      - none
  UsePermissionsBoundary: !Not
    - !Equals
      - !Ref PermissionsBoundary
      - none
  # UseTestingContainers: !Not
  #   - !Equals
  #     - !Ref TestRoleArn
  #     - none
  # IsDev: !Equals [!Ref Environment, dev]
  # IsBuild: !Equals [!Ref Environment, build]
  # IsIntegration: !Equals [!Ref Environment, integration]
  # IsStaging: !Equals [!Ref Environment, staging]
  # IsProduction: !Equals [!Ref Environment, production]
  # IsProductionPreview: !Equals [!Ref Environment, production-preview]

  # is this an environment that uses secure pipelines for deployments (production-preview does a direct sam deploy)
  # used to determine if extra policies need to be added to the secure pipelines deploy role in pipeline.yml
  # IsSecurePipelinesEnvironment: !Not [!Condition IsProductionPreview]
  # IsManualReferenceDataEnvironment: !Or
  #   - !Condition IsProduction
  #   - !Condition IsProductionPreview

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref 'AWS::NoValue'
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref 'AWS::NoValue'
    Runtime: nodejs18.x
    Timeout: 30
    CodeUri: dist/
    Environment:
      Variables:
        NODE_OPTIONS: '--enable-source-maps'
