DeployRoleExtraIAMActions:
  Type: 'AWS::IAM::ManagedPolicy'
  Properties:
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: 'VisualEditor0'
          Effect: 'Allow'
          Action:
            - 'iam:ListPolicies'
            - 'iam:ListRoles'
          Resource: '*'
        - Sid: 'VisualEditor1'
          Effect: 'Allow'
          Action:
            - 'iam:UpdateAssumeRolePolicy'
            - 'iam:GetPolicyVersion'
            - 'iam:ListRoleTags'
            - 'iam:UntagRole'
            - 'iam:TagRole'
            - 'iam:DeletePolicy'
            - 'iam:CreateRole'
            - 'iam:AttachRolePolicy'
            - 'iam:PutRolePolicy'
            - 'iam:ListInstanceProfilesForRole'
            - 'iam:PassRole'
            - 'iam:DetachRolePolicy'
            - 'iam:DeleteRolePolicy'
            - 'iam:ListAttachedRolePolicies'
            - 'iam:DetachGroupPolicy'
            - 'iam:ListPolicyTags'
            - 'iam:ListRolePolicies'
            - 'iam:CreatePolicyVersion'
            - 'iam:PutGroupPolicy'
            - 'iam:GetRole'
            - 'iam:GetPolicy'
            - 'iam:DeleteRole'
            - 'iam:UpdateRoleDescription'
            - 'iam:TagPolicy'
            - 'iam:CreatePolicy'
            - 'iam:ListPolicyVersions'
            - 'iam:AttachGroupPolicy'
            - 'iam:UntagPolicy'
            - 'iam:UpdateRole'
            - 'iam:GetGroupPolicy'
            - 'iam:DeleteGroupPolicy'
            - 'iam:GetRolePolicy'
            - 'iam:DeletePolicyVersion'
            - 'iam:GetInstanceProfile'
            - 'iam:DeleteRolePolicy'
            - 'iam:AddRoleToInstanceProfile'
            - 'iam:CreateInstanceProfile'
            - 'iam:DeleteInstanceProfile'
            - 'iam:RemoveRoleFromInstanceProfile'
          Resource:
            - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${Environment}*'
            - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/${Environment}*'
            - !Sub 'arn:aws:iam::${AWS::AccountId}:role/dap*'
            - !Sub 'arn:aws:iam::${AWS::AccountId}:role/AWS*'
            - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/dap*'
            - !Sub 'arn:aws:iam::${AWS::AccountId}:instance-profile/${Environment}*'
            - !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole'
            - !Sub 'arn:aws:iam::${AWS::AccountId}:role/*DeployRole*'
    Roles:
      - Fn::If:
          - IsFeature
          - PL-dap-feature-deploy-DeployRole-0abf029fc6b0
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsDev
          - PL-secure-pipelines-pipeline-DeployRole-0ac4f1a0d400
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsTest
          - PL-dap-test-deploy-DeployRole-022c55851b0a
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsBuild
          - PL-dap-build-deploy-DeployRole-02569a5d3e58
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsIntegration
          - PL-dap-integration-deploy-DeployRole-023e422e7530
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsStaging
          - PL-dap-staging-deploy-DeployRole-02e7fac29d94
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsProduction
          - PL-dap-production-deploy-DeployRole-068116bf8a2e
          - Ref: 'AWS::NoValue'

GluePolicy:
  Type: AWS::IAM::Policy
  Properties:
    PolicyName: 'GlueServicePolicy'
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: 'VisualEditor0'
          Effect: 'Allow'
          Action:
            - 'glue:GetCrawler'
            - 'glue:BatchGetCrawlers'
            - 'glue:DeleteCrawler'
            - 'glue:StartCrawler'
            - 'glue:StopCrawler'
            - 'glue:UpdateCrawler'
          Resource: !Sub 'arn:aws:glue:*:${AWS::AccountId}:crawler/*'
        - Sid: 'VisualEditor1'
          Effect: 'Allow'
          Action:
            - 'glue:CreateJob'
            - 'glue:UpdateJob'
            - 'glue:DeleteJob'
          Resource: !Sub 'arn:aws:glue:eu-west-2:${AWS::AccountId}:*/*'
        - Sid: 'VisualEditor2'
          Effect: 'Allow'
          Action:
            - 'glue:UpdateCrawlerSchedule'
            - 'glue:GetCrawlers'
            - 'glue:StartCrawlerSchedule'
            - 'glue:StopCrawlerSchedule'
            - 'glue:ListCrawlers'
            - 'glue:GetCrawlerMetrics'
            - 'glue:CreateCrawler'
            - 'glue:TagResource'
            - 'glue:GetTags'
          Resource: '*'
    Roles:
      - Fn::If:
          - IsFeature
          - PL-dap-feature-deploy-DeployRole-0abf029fc6b0
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsDev
          - PL-secure-pipelines-pipeline-DeployRole-0ac4f1a0d400
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsTest
          - PL-dap-test-deploy-DeployRole-022c55851b0a
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsBuild
          - PL-dap-build-deploy-DeployRole-02569a5d3e58
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsIntegration
          - PL-dap-integration-deploy-DeployRole-023e422e7530
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsStaging
          - PL-dap-staging-deploy-DeployRole-02e7fac29d94
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsProduction
          - PL-dap-production-deploy-DeployRole-068116bf8a2e
          - Ref: 'AWS::NoValue'

RedShiftEC2Policy:
  # checkov:skip=CKV_AWS_107:This check is skipped due to specific reasons
  # checkov:skip=CKV_AWS_109:This check is skipped due to specific reasons
  # checkov:skip=CKV_AWS_111:This check is skipped due to specific reasons
  Type: 'AWS::IAM::ManagedPolicy'
  Properties:
    Description: 'My Managed Policy'
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: 'VisualEditor0'
          Effect: 'Allow'
          Action:
            - 'redshift-serverless:*'
            - 'ec2:*'
            - 'scheduler:*'
          Resource: '*'
    Roles:
      - Fn::If:
          - IsFeature
          - PL-dap-feature-deploy-DeployRole-0abf029fc6b0
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsDev
          - PL-secure-pipelines-pipeline-DeployRole-0ac4f1a0d400
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsTest
          - PL-dap-test-deploy-DeployRole-022c55851b0a
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsBuild
          - PL-dap-build-deploy-DeployRole-02569a5d3e58
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsIntegration
          - PL-dap-integration-deploy-DeployRole-023e422e7530
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsStaging
          - PL-dap-staging-deploy-DeployRole-02e7fac29d94
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsProduction
          - PL-dap-production-deploy-DeployRole-068116bf8a2e
          - Ref: 'AWS::NoValue'

StateMachinePolicy:
  Type: 'AWS::IAM::ManagedPolicy'
  Properties:
    Description: 'My Managed Policy for Step Functions'
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: 'VisualEditor0'
          Effect: 'Allow'
          Action:
            - 'states:SendTaskSuccess'
            - 'states:SendTaskFailure'
            - 'states:SendTaskHeartbeat'
          Resource:
            - !Sub 'arn:aws:states:eu-west-2:${AWS::AccountId}:activity:*'
            - !Sub 'arn:aws:states:eu-west-2:${AWS::AccountId}:execution:*'
        - Sid: 'VisualEditor0List'
          Effect: 'Allow'
          Action:
            - 'states:ListStateMachines'
            - 'states:ListActivities'
          Resource: '*'
        - Sid: 'VisualEditor1'
          Effect: 'Allow'
          Action: 'states:*'
          Resource:
            - !Sub 'arn:aws:states:*:${AWS::AccountId}:execution:*:*'
            - !Sub 'arn:aws:states:*:${AWS::AccountId}:mapRun:*/*:*'
            - !Sub 'arn:aws:states:*:${AWS::AccountId}:activity:*'
            - !Sub 'arn:aws:states:*:${AWS::AccountId}:express:*:*:*'
            - !Sub 'arn:aws:states:*:${AWS::AccountId}:stateMachine:*'
    Roles:
      - Fn::If:
          - IsFeature
          - PL-dap-feature-deploy-DeployRole-0abf029fc6b0
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsDev
          - PL-secure-pipelines-pipeline-DeployRole-0ac4f1a0d400
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsTest
          - PL-dap-test-deploy-DeployRole-022c55851b0a
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsBuild
          - PL-dap-build-deploy-DeployRole-02569a5d3e58
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsIntegration
          - PL-dap-integration-deploy-DeployRole-023e422e7530
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsStaging
          - PL-dap-staging-deploy-DeployRole-02e7fac29d94
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsProduction
          - PL-dap-production-deploy-DeployRole-068116bf8a2e
          - Ref: 'AWS::NoValue'
