PipelinePolicy:
  Type: 'AWS::IAM::ManagedPolicy'
  Properties:
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: 'VisualEditor0'
          Effect: 'Allow'
          Action:
            - 'iam:ListPolicies'
            - 'iam:ListRoles'
          Resource: '*'
        - Sid: 'VisualEditor1'
          Effect: 'Allow'
          Action:
            - 'iam:UpdateAssumeRolePolicy'
            - 'iam:GetPolicyVersion'
            - 'iam:ListRoleTags'
            - 'iam:UntagRole'
            - 'iam:TagRole'
            - 'iam:DeletePolicy'
            - 'iam:CreateRole'
            - 'iam:AttachRolePolicy'
            - 'iam:PutRolePolicy'
            - 'iam:ListInstanceProfilesForRole'
            - 'iam:PassRole'
            - 'iam:DetachRolePolicy'
            - 'iam:DeleteRolePolicy'
            - 'iam:ListAttachedRolePolicies'
            - 'iam:DetachGroupPolicy'
            - 'iam:ListPolicyTags'
            - 'iam:ListRolePolicies'
            - 'iam:CreatePolicyVersion'
            - 'iam:PutGroupPolicy'
            - 'iam:GetRole'
            - 'iam:GetPolicy'
            - 'iam:DeleteRole'
            - 'iam:UpdateRoleDescription'
            - 'iam:TagPolicy'
            - 'iam:CreatePolicy'
            - 'iam:ListPolicyVersions'
            - 'iam:AttachGroupPolicy'
            - 'iam:UntagPolicy'
            - 'iam:UpdateRole'
            - 'iam:GetGroupPolicy'
            - 'iam:DeleteGroupPolicy'
            - 'iam:GetRolePolicy'
            - 'iam:DeletePolicyVersion'
            - 'iam:GetInstanceProfile'
            - 'iam:DeleteRolePolicy'
          Resource:
            - 'arn:aws:iam::999430925643:role/staging*'
            - 'arn:aws:iam::999430925643:policy/staging*'
            - 'arn:aws:iam::999430925643:role/dap*'
            - 'arn:aws:iam::999430925643:policy/dap*'
            - 'arn:aws:iam::999430925643:instance-profile/staging*'
            - 'arn:aws:iam::999430925643:role/LambdaExecutionRole'
            - 'arn:aws:iam::072886614474:role/*DeployRole*'
    Roles:
      - Fn::If:
          - IsFeature
          - PL-dap-feature-deploy-DeployRole-0abf029fc6b0
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsDev
          - PL-secure-pipelines-pipeline-DeployRole-0ac4f1a0d400
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsTest
          - PL-dap-test-deploy-DeployRole-022c55851b0a
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsBuild
          - PL-dap-build-deploy-DeployRole-02569a5d3e58
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsIntegration
          - PL-dap-integration-deploy-DeployRole-023e422e7530
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsStaging
          - PL-dap-staging-deploy-DeployRole-02e7fac29d94
          - Ref: 'AWS::NoValue'
      - Fn::If:
          - IsProduction
          - PL-dap-production-deploy-DeployRole-068116bf8a2e
          - Ref: 'AWS::NoValue'
