RawLayerBucket:
  # checkov:skip=GDS_AWS_3: Check that all S3 buckets have corresponding bucket policies
  Type: 'AWS::S3::Bucket'
  Properties:
    AccessControl: Private
    BucketName: !Sub ${Environment}-dap-raw-layer
    LoggingConfiguration:
      DestinationBucketName: !Ref GlobalLogBucket
      LogFilePrefix: dap-raw-layer/log
    PublicAccessBlockConfiguration:
      BlockPublicAcls: true
      BlockPublicPolicy: true
      IgnorePublicAcls: true
      RestrictPublicBuckets: true
    VersioningConfiguration:
      Status: Enabled

AuthAccountCreationCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: auth_account_creation
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_CREATE_ACCOUNT/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'

AuthOrchestrationCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: auth_orchestration
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_AUTHORISATION_INITIATED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'

DcmawAppJourneyCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: dcmaw_app_journey
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_ABORT_APP/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_ABORT_WEB/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_APP_END/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_APP_HANDOFF_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_APP_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_MISSING_CONTEXT_AFTER_ABORT/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_MISSING_CONTEXT_AFTER_COMPLETION/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_REDIRECT_ABORT/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_REDIRECT_SUCCESS/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_SESSION_RECOVERED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_WEB_END/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'

DcmawCriCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: dcmaw_cri
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_BRP_SELECTED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_CRI_4XXERROR/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_CRI_5XXERROR/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_CRI_ABORT/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_CRI_END/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_CRI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_CRI_VC_ISSUED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_DRIVING_LICENCE_SELECTED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_HYBRID_BILLING_STARTED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_IPROOV_BILLING_STARTED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_PASSPORT_SELECTED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_READID_NFC_BILLING_STARTED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'

IpvCriAddressCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_cri_address
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_ADDRESS_CRI_END/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_ADDRESS_CRI_REQUEST_SENT/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_ADDRESS_CRI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_ADDRESS_CRI_VC_ISSUED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'

IpvContraIndicatorCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_contra_indicator
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_CRI_AUTH_RESPONSE_RECEIVED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'

IpvCriFraudCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_cri_fraud
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_FRAUD_CRI_END/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_FRAUD_CRI_REQUEST_SENT/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_FRAUD_CRI_RESPONSE_RECEIVED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_FRAUD_CRI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_FRAUD_CRI_THIRD_PARTY_REQUEST_ENDED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_FRAUD_CRI_VC_ISSUED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'

IpvJourneyCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_journey
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_DELETE_USER_DATA/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_IDENTITY_REUSE_COMPLETE/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_IDENTITY_REUSE_RESET/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_JOURNEY_END/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_JOURNEY_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_REDIRECT_TO_CRI/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_VC_RECEIVED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_SPOT_REQUEST_RECEIVED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_SPOT_RESPONSE_APPROVED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_SPOT_RESPONSE_REJECTED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'

IpvCriKbvCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_cri_kbv
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_KBV_CRI_END/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_KBV_CRI_REQUEST_SENT/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_KBV_CRI_RESPONSE_RECEIVED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_KBV_CRI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_KBV_CRI_THIRD_PARTY_REQUEST_ENDED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_KBV_CRI_VC_ISSUED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'

IpvCriPassportCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_cri_passport
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_PASSPORT_CRI_END/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_PASSPORT_CRI_REQUEST_SENT/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_PASSPORT_CRI_RESPONSE_RECEIVED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_PASSPORT_CRI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_PASSPORT_CRI_VC_ISSUED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'

RawGlueCrawlerRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: !Sub ${Environment}-raw-glue-crawler-role
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service: [glue.amazonaws.com]
          Action: ['sts:AssumeRole']
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
    Path: /
    Policies:
      - PolicyName: !Sub ${Environment}-raw-glue-crawler-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'glue:GetConnection'
                - 'glue:GetCrawler'
                - 'glue:CreateTable'
                - 'glue:UpdateCrawler'
                - 'glue:CreatePartition'
                - 'glue:BatchCreatePartition'
              Resource: '*'
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
                - 's3:ListObject'
              Resource:
                - !Sub 'arn:aws:s3:::${RawLayerBucket}'
                - !Sub 'arn:aws:s3:::${RawLayerBucket}/*'

RawGlueDatabase:
  Type: AWS::Glue::Database
  Properties:
    CatalogId: !Sub ${AWS::AccountId}
    DatabaseInput:
      Name: !Sub ${Environment}-${RawGlueDatabaseName}
