RawLayerBucket:
  Type: 'AWS::S3::Bucket'
  Properties:
    AccessControl: Private
    BucketName: !Sub ${Environment}-dap-raw-layer
    LoggingConfiguration:
      DestinationBucketName: !Ref GlobalLogBucket
      LogFilePrefix: dap-raw-layer/log
    PublicAccessBlockConfiguration:
      BlockPublicAcls: true
      BlockPublicPolicy: true
      IgnorePublicAcls: true
      RestrictPublicBuckets: true
    VersioningConfiguration:
      Status: Enabled
    LifecycleConfiguration:
      Rules:
        - ExpirationInDays: 365
          Status: Enabled
    NotificationConfiguration:
      LambdaConfigurations:
        - Event: s3:ObjectCreated:*
          Function: !GetAtt S3NotificationsLoggerLambda.Arn
        - Event: s3:ObjectRemoved:*
          Function: !GetAtt S3NotificationsLoggerLambda.Arn

RawLayerBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref RawLayerBucket
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Deny
          Action: 's3:*'
          Resource: !Sub ${RawLayerBucket.Arn}/*
          Principal: '*'
          Condition:
            Bool:
              aws:SecureTransport: false
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:ListBucket'
          Resource:
            - !Sub ${RawLayerBucket.Arn}
            - !Sub ${RawLayerBucket.Arn}/*
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root

AuthAccountUserLoginCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: auth_account_user_login
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_CHECK_USER_KNOWN_EMAIL/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_LOG_IN_SUCCESS/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_AUTH_CODE_ISSUED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

AuthAccountCreationCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: auth_account_creation
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_CHECK_USER_NO_ACCOUNT_WITH_EMAIL/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_CREATE_ACCOUNT/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

AuthAccountManagementCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: auth_account_management
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_PASSWORD_RESET_SUCCESSFUL/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

AuthAccountMfaCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: auth_account_mfa
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_CODE_VERIFIED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

AuthOrchestrationCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: auth_orchestration
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_AUTHORISATION_INITIATED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_AUTHORISATION_REQUEST_ERROR/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_AUTHORISATION_REQUEST_RECEIVED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/AUTH_IPV_AUTHORISATION_REQUESTED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

DcmawCriCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: dcmaw_cri
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_APP_END'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_APP_HANDOFF_START'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_APP_START'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_CRI_START'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_CRI_VC_ISSUED'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_DRIVING_LICENCE_SELECTED'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_PASSPORT_SELECTED'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_WEB_END/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/DCMAW_BRP_SELECTED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

IpvCriAddressCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_cri_address
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_ADDRESS_CRI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_ADDRESS_CRI_VC_ISSUED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_ADDRESS_CRI_END/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_ADDRESS_CRI_REQUEST_SENT/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

IpvCriDrivingLicenseCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_cri_driving_license
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_DL_CRI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_DL_CRI_VC_ISSUED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

IpvCriFraudCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_cri_fraud
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_FRAUD_CRI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_FRAUD_CRI_VC_ISSUED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_FRAUD_CRI_REQUEST_SENT/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_FRAUD_CRI_RESPONSE_RECEIVED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_FRAUD_CRI_THIRD_PARTY_REQUEST_ENDED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

IpvCriKbvCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_cri_kbv
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_KBV_CRI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_KBV_CRI_VC_ISSUED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

IpvCriPassportCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_cri_passport
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_PASSPORT_CRI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_PASSPORT_CRI_VC_ISSUED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

IpvJourneyCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_journey
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_IDENTITY_REUSE_COMPLETE/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_IDENTITY_REUSE_RESET/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_JOURNEY_END/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_JOURNEY_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_SPOT_RESPONSE_APPROVED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_SPOT_RESPONSE_REJECTED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

IpvCriCicCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_cri_cic
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/CIC_CRI_AUTH_CODE_ISSUED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/CIC_CRI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/CIC_CRI_VC_ISSUED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

IpvCriFtofCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_cri_ftof
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      S3Targets:
        - Path: !Sub 's3://${RawLayerBucket}/txma/F2F_CRI_AUTH_CODE_ISSUED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/F2F_CRI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/F2F_CRI_VC_ISSUED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/F2F_YOTI_END/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/F2F_YOTI_PDF_EMAILED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/F2F_YOTI_START/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPR_RESULT_NOTIFICATION_EMAILED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPR_USER_REDIRECTED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_F2F_CRI_VC_CONSUMED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/IPV_F2F_CRI_VC_RECEIVED/'
        - Path: !Sub 's3://${RawLayerBucket}/txma/F2F_YOTI_RESPONSE_RECEIVED/'
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: UPDATE_IN_DATABASE
      DeleteBehavior: DELETE_FROM_DATABASE
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'

FtofCriVcIssuedGlueTable:
  Type: AWS::Glue::Table
  Properties:
    CatalogId: !Sub ${AWS::AccountId}
    DatabaseName: !Ref RawGlueDatabase
    TableInput:
      Name: ftof_cri_vc_issued
      TableType: EXTERNAL_TABLE
      PartitionKeys:
        - { Name: year, Type: int }
        - { Name: month, Type: int }
        - { Name: day, Type: int }
      StorageDescriptor:
        Columns:
          - { Name: event_id, Type: string }
          - { Name: event_name, Type: string }
          - { Name: client_id, Type: string }
          - { Name: component_id, Type: string }
          - { Name: user, Type: 'struct<govuk_signin_journey_id:string,user_id:string>' }
          - { Name: timestamp, Type: int }
          - { Name: timestamp_formatted, Type: string }
          - { Name: txma, Type: 'struct<configVersion:string>' }
          - {
              Name: extensions,
              Type: 'struct<previous_govuk_signin_journey_id:string,evidence:array<struct<checkDetails:array<struct<biometricVerificationProcessLevel:int,checkMethod:string,photoVerificationProcessLevel:int>>,strengthScore:int,type:string,validityScore:int,verificationScore:int>>>',
            }
          - {
              Name: restricted,
              Type: 'struct<passport:array<struct<documentType:string>>,residencePermit:array<struct<documentType:string>>,drivingPermit:array<struct<documentType:string>>,idCard:array<struct<documentType:string>>>',
            }
        InputFormat: org.apache.hadoop.mapred.TextInputFormat
        Location: !Sub s3://${RawLayerBucket}/txma/F2F_CRI_VC_ISSUED/
        OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
        SerdeInfo:
          Parameters:
            serialiazation.format: 1
          SerializationLibrary: org.openx.data.jsonserde.JsonSerDe

FtofCrawler:
  Type: AWS::Glue::Crawler
  Properties:
    Name: ipv_cri_ftof_fixed
    Role: !GetAtt RawGlueCrawlerRole.Arn
    Targets:
      CatalogTargets:
        - DatabaseName: !Ref RawGlueDatabase
          Tables:
            - !Ref FtofCriVcIssuedGlueTable
    DatabaseName: !Ref RawGlueDatabase
    CrawlerSecurityConfiguration: !Ref GlueSecurityConfig
    RecrawlPolicy:
      RecrawlBehavior: CRAWL_EVERYTHING
    SchemaChangePolicy:
      UpdateBehavior: LOG
      DeleteBehavior: LOG
    Configuration: '{"Version":1,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'

RawGlueCrawlerRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: !Sub ${Environment}-raw-glue-crawler-role
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service: [glue.amazonaws.com]
          Action: ['sts:AssumeRole']
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
    Path: /
    Policies:
      - PolicyName: !Sub ${Environment}-raw-glue-crawler-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'glue:GetConnection'
                - 'glue:GetCrawler'
                - 'glue:CreateTable'
                - 'glue:UpdateCrawler'
                - 'glue:CreatePartition'
                - 'glue:BatchCreatePartition'
              Resource: '*'
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
                - 's3:ListObject'
              Resource:
                - !Sub 'arn:aws:s3:::${RawLayerBucket}'
                - !Sub 'arn:aws:s3:::${RawLayerBucket}/*'
            - Effect: Allow
              Action: 'logs:AssociateKmsKey'
              Resource: 'arn:aws:logs:*:*:/aws-glue/*'

RawGlueDatabase:
  Type: AWS::Glue::Database
  Properties:
    CatalogId: !Sub ${AWS::AccountId}
    DatabaseInput:
      Name: !Sub ${Environment}-${RawGlueDatabaseName}
