IAMRoleRedshiftServerless:
  Type: 'AWS::IAM::Role'
  Properties:
    RoleName: !Sub ${Environment}-redshift-serverless-role
    AssumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            Service: [firehose.amazonaws.com,redshift.amazonaws.com,glue.amazonaws.com,redshift-serverless.amazonaws.com]
          Action: 'sts:AssumeRole'
    MaxSessionDuration: 3600
    Policies:
      - PolicyName: !Sub ${Environment}-redshift-serverless-policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - 's3:AbortMultipartUpload'
                - 's3:GetBucketLocation'
                - 's3:GetObject'
                - 's3:ListBucket'
                - 's3:ListBucketMultipartUploads'
                - 's3:PutObject'
              Resource:
                - !Sub 'arn:aws:s3:::${RawLayerBucket}'
                - !Sub 'arn:aws:s3:::${RawLayerBucket}/*'
                - !Sub 'arn:aws:s3:::${StageLayerBucket}'
                - !Sub 'arn:aws:s3:::${StageLayerBucket}/*'                
            - Effect: Allow
              Resource: !Sub arn:aws:glue:eu-west-2:${AWS::AccountId}:*
              Action:
                - 'glue:GetTable'
                - 'glue:GetTables'
                - 'glue:GetDatabase'
                - 'glue:GetDatabases'

MyRedshiftSecret:
  # checkov:skip=CKV_AWS_149: "Ensure that Secrets Manager secret is encrypted using KMS CMK"
  Type: 'AWS::SecretsManager::Secret'
  Properties:
    Description: This is a Secrets Manager secret for a Redshift cluster
    GenerateSecretString:
      SecretStringTemplate: '{"username": "admin"}'
      GenerateStringKey: password
      PasswordLength: 16
      ExcludeCharacters: '"''@/\'

VPCForDAP:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: 10.0.0.0/16
    Tags:
      - Key: Environment
        Value: !Ref Environment

SubnetForDAP1:
  Type: AWS::EC2::Subnet
  Properties:
    VpcId: !Ref VPCForDAP
    AvailabilityZone: !Select
      - 0
      - !GetAZs
        Ref: 'AWS::Region'
    CidrBlock: 10.0.1.0/24
    Tags:
      - Key: Environment
        Value: !Ref Environment

SubnetForDAP2:
  Type: AWS::EC2::Subnet
  Properties:
    VpcId: !Ref VPCForDAP
    AvailabilityZone: !Select
      - 1
      - !GetAZs
        Ref: 'AWS::Region'
    CidrBlock: 10.0.2.0/24
    Tags:
      - Key: Environment
        Value: !Ref Environment

SubnetForDAP3:
  Type: AWS::EC2::Subnet
  Properties:
    VpcId: !Ref VPCForDAP
    AvailabilityZone: !Select
      - 2
      - !GetAZs
        Ref: 'AWS::Region'
    CidrBlock: 10.0.3.0/24
    Tags:
      - Key: Environment
        Value: !Ref Environment

RouteTableForDAP:
  Type: AWS::EC2::RouteTable
  Properties:
    Tags:
      - Key: Environment
        Value: !Ref Environment
    VpcId: !Ref VPCForDAP

SubnetRouteTableAssocDAP1:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
    RouteTableId: !Ref RouteTableForDAP
    SubnetId: !Ref SubnetForDAP1

SubnetRouteTableAssocDAP2:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
    RouteTableId: !Ref RouteTableForDAP
    SubnetId: !Ref SubnetForDAP2
    
SubnetRouteTableAssocDAP3:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
    RouteTableId: !Ref RouteTableForDAP
    SubnetId: !Ref SubnetForDAP3

RedshiftServerlessNamespace:
  Type: 'AWS::RedshiftServerless::Namespace'
  Properties:
    AdminUsername:
      'Fn::Sub': '{{resolve:secretsmanager:${MyRedshiftSecret}::username}}'
    AdminUserPassword:
      'Fn::Sub': '{{resolve:secretsmanager:${MyRedshiftSecret}::password}}'
    DbName: !Sub '${Environment}-redshift'
    DefaultIamRoleArn: !GetAtt IAMRoleRedshiftServerless.Arn
    IamRoles:
      - !GetAtt IAMRoleRedshiftServerless.Arn
    FinalSnapshotName: !Sub '${Environment}-redshift-snapshot'
    FinalSnapshotRetentionPeriod: 30
    LogExports:
      - useractivitylog
    NamespaceName: !Sub '${Environment}-redshift-serverless-namespace'

RedshiftServerlessWorkgroup:
  Type: 'AWS::RedshiftServerless::Workgroup'
  Properties:
    BaseCapacity: 128
    EnhancedVpcRouting: false
    NamespaceName: !Ref RedshiftServerlessNamespace
    Port: 5439
    PubliclyAccessible: false
    SubnetIds:
      - !Ref SubnetForDAP1
      - !Ref SubnetForDAP2
      - !Ref SubnetForDAP3
    WorkgroupName: !Sub '${Environment}-redshift-serverless-workgroup'
