AWSTemplateFormatVersion: 2010-09-09
Description: Quicksight Access Stack
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: Environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - feature
      - build
      - staging
      - integration
      - production
  CodeSigningConfigArn:
    Description: ARN of Code Signing Config from deployment pipeline
    Type: String
    Default: none
  PermissionsBoundary:
    Description: ARN of permissions boundary for new roles
    Type: String
    Default: none

Conditions:
  UseCodeSigning: !Not
    - !Equals
      - !Ref CodeSigningConfigArn
      - none
  UsePermissionsBoundary: !Not
    - !Equals
      - !Ref PermissionsBoundary
      - none
  IsTest: !Equals [!Ref Environment, test]
  IsFeature: !Equals [!Ref Environment, feature]
  IsDev: !Equals [!Ref Environment, dev]
  IsProduction: !Equals [!Ref Environment, production]
  IsQuicksightEnvironment: !Or
    - !Condition IsDev
    - !Condition IsTest
    - !Condition IsFeature
    - !Condition IsProduction
  IsDevOrProd: !Or
    - !Condition IsDev
    - !Condition IsProduction

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref 'AWS::NoValue'
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref 'AWS::NoValue'
    Runtime: nodejs18.x
    Timeout: 30
    CodeUri: dist/
    Environment:
      Variables:
        NODE_OPTIONS: '--enable-source-maps'
