name: ✳️ Add user to Quicksight

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: AWS Environment
        options: [DEV, TEST, FEATURE, PRODUCTION, PRODUCTION-PREVIEW]
        default: PRODUCTION
      email:
        type: string
        required: true
        description: Email address
      username:
        type: string
        required: false
        description: Username (defaults to email address)
      group:
        type: choice
        required: true
        description: Quicksight group
        options: [gds-users, dbs, dvsa, hmlr, hmrc, swe, veterans]

jobs:
  invoke-add-users-lambda:
    # These permissions are needed to interact with GitHub's OIDC Token endpoint (enabling the aws-actions/configure-aws-credentials action)
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get role name
        run: |
          # github doesn't allow secrets with hyphens so we need to make sure the role name
          # becomes QUICKSIGHT_LAMBDAS_INVOKE_ROLE_PRODUCTION_PREVIEW instead of QUICKSIGHT_LAMBDAS_INVOKE_ROLE_PRODUCTION-PREVIEW
          ENVIRONMENT_NO_HYPHEN=$(echo ${{ inputs.environment }} | sed 's/-/_/g')
          echo "ROLE_NAME=QUICKSIGHT_LAMBDAS_INVOKE_ROLE_$ENVIRONMENT_NO_HYPHEN" >> $GITHUB_ENV
      - name: Assume AWS Quicksight lambdas role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets[env.ROLE_NAME] }}
      - name: Invoke lambda
        run: |
          USERNAME=$(if [ -z ${{ inputs.username }} ]; then echo ${{ inputs.email }}; else echo ${{ inputs.username }}; fi)
          PAYLOAD=$(echo "{\"requests\": [{ \"username\": \"$USERNAME\", \"email\": \"${{ inputs.email }}\", \"quicksightGroups\": [\"${{ inputs.group }}\"] }] }")
          echo "Lambda request"
          echo "$PAYLOAD" | jq

          ENCODED=$(echo "$PAYLOAD" | openssl base64)
          echo -e "\nLambda invocation"
          aws --region eu-west-2 lambda invoke --function-name quicksight-add-users --payload "$ENCODED" out.json

          echo -e "\nLambda response"
          cat out.json | jq
