name: Manually deploy to the dev environment

on: workflow_dispatch

jobs:
  test-and-validate:
    secrets: inherit
    uses: ./.github/workflows/test-and-validate.yml

  deploy-to-dev:
    needs: [test-and-validate]
    # These permissions are needed to interact with GitHub's OIDC Token endpoint (enabling the aws-actions/configure-aws-credentials action)
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install node packages
        run: npm ci
      - name: Build lambdas
        run: npm run build
      - name: SAM setup
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.82.0
      - name: SAM build
        run: sam build
      - name: Assume AWS GitHub actions role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN_DEV }}
      - name: Trigger secure pipeline deployment
        uses: alphagov/di-devplatform-upload-action@v3.2
        with:
          artifact-bucket-name: ${{ secrets.ARTIFACT_BUCKET_NAME_DEV }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME_DEV }}
          working-directory: .
