name: ✳️ Deploy to the production preview environment

on:
  workflow_dispatch:
    inputs:
      skip-s3-upload:
        type: boolean
        required: false
        description: Skip uploading athena files to S3

jobs:
  deploy-to-production-preview:
    # These permissions are needed to interact with GitHub's OIDC Token endpoint (enabling the aws-actions/configure-aws-credentials action)
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    uses: ./.github/workflows/sam-deploy.yml
    with:
      lowercase-environment: production-preview

  upload-athena-files:
    if: inputs.skip-s3-upload == false
    # These permissions are needed to interact with GitHub's OIDC Token endpoint (enabling the aws-actions/configure-aws-credentials action)
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    uses: ./.github/workflows/upload-athena-files.yml
    with:
      environment: PRODUCTION-PREVIEW
