name: Deploy to the test environment

on: workflow_dispatch

jobs:
  test-and-validate:
    secrets: inherit
    uses: ./.github/workflows/test-and-validate.yml

  deploy-to-test:
    needs: [test-and-validate]
    # These permissions are needed to interact with GitHub's OIDC Token endpoint (enabling the aws-actions/configure-aws-credentials action)
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    uses: ./.github/workflows/deploy-to-aws.yml
    with:
      environment: TEST
