name: ✳️ Deploy to the dev environment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-validate:
    secrets: inherit
    uses: ./.github/workflows/test-and-validate.yml

  deploy-to-dev:
    needs: [test-and-validate]
    # These permissions are needed to interact with GitHub's OIDC Token endpoint (enabling the aws-actions/configure-aws-credentials action)
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    uses: ./.github/workflows/deploy-to-aws.yml
    with:
      environment: DEV
