name: ✳️ Pull request deploy and test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - '**.md'

jobs:
  validate-deployment-or-teardown:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.validate.outputs.valid }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - id: validate
        name: Validate branch eligibility for deployment
        run: scripts/validate-deployment-or-teardown.sh ${{ github.head_ref }} >> $GITHUB_OUTPUT

  deploy-to-feature:
    needs: [validate-deployment-or-teardown]
    if: needs.validate-deployment-or-teardown.outputs.valid == 'true'
    # These permissions are needed to interact with GitHub's OIDC Token endpoint (enabling the aws-actions/configure-aws-credentials action)
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    uses: ./.github/workflows/deploy-to-aws.yml
    with:
      environment: FEATURE
      skip-s3-upload: true

  run-integration-tests:
    needs: [deploy-to-feature]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests
        run: echo running tests for pr https://github.com/alphagov/di-data-analytics-platform/pull/${{ github.event.pull_request.number }}
