name: ✳️ Pull request deploy and test

on:
  workflow_dispatch:
    inputs:
      skip-tests:
        description: Skip running the smoke and integration tests (i.e. just deploy to feature)
        type: boolean
        required: false
        default: false
  pull_request_review:
    types:
      - submitted
    paths-ignore:
      - '**.md'

jobs:
  validate-deployment-or-teardown:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.validate.outputs.valid }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - id: validate
        name: Validate branch eligibility for deployment
        run: |
          # when this workflow is run on the workflow_dispatch event, ref_name will be set to the branch name
          # however when it is run on the pull_request_review event then ref_name will be something like '123/merge' (the pr number)
          # but the pull_request_review event includes a pull_request event not present on workflow_dispatch
          # we can use the head.ref property of this to get the branch name
          # see https://docs.github.com/en/webhooks/webhook-events-and-payloads
          REF=${{ github.event.pull_request && github.event.pull_request.head.ref || github.ref_name }}
          echo "ref = $REF"
          scripts/validate-deployment-or-teardown.sh "$REF" >> $GITHUB_OUTPUT

  deploy-to-feature:
    needs: [validate-deployment-or-teardown]
    if: needs.validate-deployment-or-teardown.outputs.valid == 'true'
    # These permissions are needed to interact with GitHub's OIDC Token endpoint (enabling the aws-actions/configure-aws-credentials action)
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    uses: ./.github/workflows/sam-deploy.yml
    with:
      lowercase-environment: feature

  run-integration-tests:
    if: inputs.skip-tests == false
    needs: [deploy-to-feature]
    # These permissions are needed to interact with GitHub's OIDC Token endpoint (enabling the aws-actions/configure-aws-credentials action)
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.FEATURE_ENVIRONMENT_TEAR_DOWN_ROLE_ARN }}
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install node packages
        run: npm ci
      - name: Correct environment in jest.setup.js
        run: sed -i 's/dev/feature/' jest.setup.js
        # todo remove the `-- --testPathIgnorePatterns=redshift` below once redshift works in the feature environment
      - name: Run integration tests
        run: npm run integration-test -- --testPathIgnorePatterns=redshift
        env:
          ENVIRONMENT: feature
          TXMA_BUCKET: feature-dap-raw-layer
          TXMA_QUEUE_URL: https://sqs.eu-west-2.amazonaws.com/655068466146/feature-placeholder-txma-event-queue

  run-smoke-tests:
    if: inputs.skip-tests == false
    needs: [deploy-to-feature]
    # These permissions are needed to interact with GitHub's OIDC Token endpoint (enabling the aws-actions/configure-aws-credentials action)
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.FEATURE_ENVIRONMENT_TEAR_DOWN_ROLE_ARN }}
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install node packages
        run: npm ci
      - name: Correct environment in jest.setup.js
        run: sed -i 's/dev/feature/' jest.setup.js
      - name: Run smoke tests
        run: npm run smoke-test
        env:
          ENVIRONMENT: feature
          TXMA_BUCKET: feature-dap-raw-layer
          TXMA_QUEUE_URL: https://sqs.eu-west-2.amazonaws.com/655068466146/feature-placeholder-txma-event-queue
