name: Tear down

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  tear-down-cf-stack:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.integration_test-stacks-role }} 
      - name: Empty S3 buckets in the stack
        run: npm run s3:empty-buckets
      - name: Delete CF stack
        run: sam delete --stack-name dap --no-prompts --region eu-west-2