name: Test and validate iac and lambdas

on:
  pull_request:
      paths-ignore:
        - '**.md'
  workflow_call:
  workflow_dispatch:

jobs:
  validate-iac:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install node packages
        run: npm ci
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Install SAM and Checkov
        run: pip install -r requirements.txt
      - name: IaC formatting checks
        run: npm run iac:format:check
      - name: IaC linting checks
        run: npm run iac:lint
      - name: Check out checkov hooks repository code
        uses: actions/checkout@v3
        with:
          repository: alphagov/di-devplatform-checkov-hook
          token: ${{ secrets.CHECKOUT_REPO_PAT }}
          path: di-devplatform-checkov-hook
      - name: Checkov scan
        env:
          CHECKS_BASE_DIR: di-devplatform-checkov-hook/src/gds_digitalidentity_checkovhook
        run: checkov --external-checks-dir $CHECKS_BASE_DIR/custom_policies --external-checks-dir $CHECKS_BASE_DIR/custom_policies_precommit --file template.yaml --quiet

  validate-lambdas:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install node packages
        run: npm ci
      - name: Run linting and formatting
        run: npm run check
      - name: Run tests
        run: npm run test
