name: ✳️ Upload Athena files to S3

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: AWS environment
        options: [DEV, TEST, FEATURE, BUILD, STAGING, INTEGRATION, PRODUCTION, PRODUCTION-PREVIEW]

jobs:
  validate-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Validate input environment
        run: scripts/validate-environment.sh ${{ inputs.environment }}

  upload-to-s3:
    needs: [validate-environment]
    # These permissions are needed to interact with GitHub's OIDC Token endpoint (enabling the aws-actions/configure-aws-credentials action)
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Assume AWS GitHub actions role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.ELT_METADATA_UPLOAD_ROLE_ARN }}
      - name: Upload athena files to S3
        run: scripts/athena-upload.sh ${{ inputs.environment }}
